server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.3.10:8848
      discovery:
        namespace: 72940da3-ed15-4bbe-9cd4-b1fd3b03d733
    gateway:
      routes:
        - id: login-service
          uri: lb://loginservice
          predicates:
            - Path=/login/**
        - id: goods-service
          uri: lb://goodsservice
          predicates:
            - Path=/goods/**
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
        - id: seckillservice
          uri: lb://seckillservice
          predicates:
            - Path=/seckill/**