spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill_demo?useSSL=false
    username: root
    password: 102700
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: seckillservice
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 192.168.3.10:8848
      discovery:
        namespace: 72940da3-ed15-4bbe-9cd4-b1fd3b03d733
      config:
        file-extension: yaml
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
  #RabbitMQ配置
  rabbitmq:
    host: 192.168.3.10
    username: admin
    password: 102700
    #虚拟主机
    virtual-host: /VHOST
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只处理一条信息，处理完再继续下一条信息
        prefetch: 1
        #启动时是否默认启动容器
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认true
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000
        #重试最大次数，默认3次
        max-attempts: 3
        #重试最大间隔时间，默认10000ms
        max-interval: 10000
        #重试间隔的乘数。比如配2.0 第一次等10s，第二次等20s，第三次等40s
        multiplier: 1.0

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8080

goodsservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

orderservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

ribbon:
  eager-load:
    enabled: true
    clients:
      - goodsservice
      - orderservice
feign:
  client:
    config:
      default:
        loggerLevel: BASIC #日志级别，BASIC就是基本的请求和响应信息
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50