spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill_demo?useSSL=false
    username: root
    password: 102700
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: loginservice
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 192.168.3.10:8848
      discovery:
        namespace: 72940da3-ed15-4bbe-9cd4-b1fd3b03d733
      config:
        file-extension: yaml
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8082